import "dotenv/config";
import { db } from "../src/lib/db";
import { calculateAndPersistPlayerOpportunity } from "../src/lib/intelligence/persistence";
import { playerScopeWhere, saveProfile } from "../src/lib/services/players";
import { finishRun, withSyncLock } from "../src/lib/services/runs";
import { TransfermarktClient } from "../src/lib/transfermarkt/client";
import { BudgetError, ProviderError } from "../src/lib/transfermarkt/errors";
import { TransfermarktProvider } from "../src/lib/transfermarkt/provider";
const MAX=100;
const valid=(p:any)=>/^\d+$/.test(p.tmPlayerId)&&/^https?:\/\/(?:www\.)?transfermarkt\.[^/]+\/.+\/profil\/spieler\/\d+/i.test(p.tmUrl);
const role=(p:any)=>!!p.mainPosition?.trim()&&p.mainPosition.trim().toUpperCase()!=="UNKNOWN";
const age=(p:any)=>p.birthDate!==null||p.age!==null;
const fields=(p:any)=>({age:age(p),role:role(p),photo:!!p.portraitUrl?.trim(),foot:["LEFT","RIGHT"].includes(p.preferredFoot),contract:p.contractExpires!==null,value:p.marketValueEur!==null,representation:p.representationStatus!=="UNKNOWN"});
async function main(){await withSyncLock(async()=>{const select={id:true,name:true,tmPlayerId:true,tmUrl:true,birthDate:true,age:true,mainPosition:true,portraitUrl:true,preferredFoot:true,contractExpires:true,marketValueEur:true,representationStatus:true,profileLastSyncedAt:true};const all=await db.player.findMany({where:playerScopeWhere("UZBEKISTAN"),select});const before=all.map(fields), count=(x:any[],k:string)=>x.filter(p=>p[k]).length;const skipped=all.filter(p=>!role(p)&&!valid(p));const targets=all.filter(p=>!role(p)&&valid(p)).sort((a,b)=>{const ma=Object.values(fields(a)).filter(v=>!v).length,mb=Object.values(fields(b)).filter(v=>!v).length;return Number(a.profileLastSyncedAt!==null)-Number(b.profileLastSyncedAt!==null)||mb-ma||Number(a.profileLastSyncedAt!==null)-Number(b.profileLastSyncedAt!==null)||a.name.localeCompare(b.name)}).slice(0,MAX);console.log(JSON.stringify({unknownRole:targets.length+skipped.length,selected:targets.length,skipped:skipped.length,before:{age:count(before,"age"),role:count(before,"role"),photo:count(before,"photo"),foot:count(before,"foot"),contract:count(before,"contract"),value:count(before,"value"),representation:count(before,"representation")}}));const run=await db.syncRun.create({data:{type:"UZ1_UNKNOWN_ROLE_PROFILE_ENRICHMENT",metadata:JSON.stringify({targets:targets.map(p=>p.id)})}});const provider=new TransfermarktProvider(new TransfermarktClient(run.id,MAX));let consecutive404=0,zero=0,success=0,failed=0,stop="completed target";const results:any[]=[];for(const [i,p] of targets.entries()){const prior=fields(p);try{const saved=await saveProfile(await provider.fetchPlayerProfile(p.tmPlayerId,p.tmUrl));await db.player.update({where:{id:saved.id},data:{preferredFootSyncedAt:new Date()}});await calculateAndPersistPlayerOpportunity(saved.id);const after=fields(await db.player.findUniqueOrThrow({where:{id:saved.id},select}));const gained=Object.keys(after).filter(k=>!prior[k as keyof typeof prior]&&after[k as keyof typeof after]);success++;zero=gained.length?0:zero+1;results.push({name:p.name,http:200,ageGained:!prior.age&&after.age,roleGained:!prior.role&&after.role,gained});if(zero>=3){stop="three successful profiles gained zero fields";break}}catch(e){failed++;const status=e instanceof ProviderError?e.status:undefined;results.push({name:p.name,http:status??"error",ageGained:false,roleGained:false,gained:[]});consecutive404=status===404?consecutive404+1:0;if(status===403||status===429||consecutive404>=3||e instanceof BudgetError){stop=status===403?"403":status===429?"429":consecutive404>=3?"three consecutive 404":"budget";break}}if(i===2){const usable=results.filter(r=>r.http===200&&r.gained.length>0).length, gains=results.filter(r=>r.ageGained||r.roleGained).length;if(usable<2||gains<2){stop="canary failed";break}}}await finishRun(run.id,undefined,{stop,results,success,failed});console.log(JSON.stringify({stop,success,failed,results},null,2))})}
try{await main()}finally{await db.$disconnect()}
