import "dotenv/config";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { playerUrl } from "../src/lib/transfermarkt/endpoints";
import { parseProfile } from "../src/lib/transfermarkt/parsers/profile";
const input="src/data/import/ita-expat/famosoccer_italiani_estero_2026_27_PARTIAL_CORRETTO_MAX.json";
const output="src/data/import/ita-expat/famosoccer_italiani_estero_2026_27_ENRICHED_FULL.json";
const checkpointPath="src/data/import/ita-expat/.ita-profile-enrichment-checkpoint.json";
const args=process.argv.slice(2); const at=args.indexOf("--limit"); const limit=at>=0?Number(args[at+1]):Infinity;
const base=JSON.parse(readFileSync(input,"utf8")); const checkpoint=existsSync(checkpointPath)?JSON.parse(readFileSync(checkpointPath,"utf8")):{processedTmPlayerIds:[],successTmPlayerIds:[],failedTmPlayerIds:[],lastProcessedIndex:-1,startedAt:new Date().toISOString(),fieldsFilled:0}; checkpoint.fieldsFilled ??= 0;
const result=existsSync(output)?JSON.parse(readFileSync(output,"utf8")):base;
const fields=["birthDate","birthPlace","nationalities","heightCm","preferredFoot","mainPosition","positionGroup","secondaryPositions","shirtNumber","joinedDate","contractExpires","contractOption","marketValueEur","marketValueRaw","agentRaw","agencyName","representationStatus","portraitUrl","careerStatus"] as const;
const good=(v:any,k:string)=>v!==null&&v!==undefined&&v!==""&&v!=="[]"&&!(k==="portraitUrl"&&String(v).includes("default.jpg"))&&!(String(v)==="UNKNOWN");
const missing=(p:any)=>fields.filter(k=>!good(p[k],k)).length;
const save=()=>{checkpoint.updatedAt=new Date().toISOString();result.metadata.profileEnrichment={startedAt:checkpoint.startedAt,totalPlayers:result.players.length,attempted:checkpoint.processedTmPlayerIds.length,succeeded:checkpoint.successTmPlayerIds.length,failed:checkpoint.failedTmPlayerIds.length,fieldsFilled:checkpoint.fieldsFilled??0,stoppedReason:checkpoint.stoppedReason??null};writeFileSync(output,JSON.stringify(result,null,2));writeFileSync(checkpointPath,JSON.stringify(checkpoint,null,2));};
async function main(){const queue=[...result.players].sort((a:any,b:any)=>missing(b)-missing(a));for(let i=0,attempts=0;i<queue.length&&attempts<limit;i++){const p=queue[i]; if(checkpoint.successTmPlayerIds.includes(p.tmPlayerId)) continue; attempts++;console.log(`[${i+1}/${queue.length}] ${p.name}\ntmPlayerId: ${p.tmPlayerId}\nmissing before: ${missing(p)}`);try{const parsed=playerUrl(p.tmUrl); const response=await fetch(`https://www.transfermarkt.it${parsed.path}`,{headers:{"User-Agent":"Famosoccer/0.1","Accept-Language":"it-IT,it;q=0.9"}}); const body=await response.text(); if(!response.ok) throw Object.assign(new Error(`HTTP ${response.status}`),{status:response.status}); const profile=parseProfile(body,p.tmPlayerId,p.tmUrl);let filled=0;for(const key of fields){const incoming=(profile as any)[key];if(!good(p[key],key)&&good(incoming,key)){p[key]=incoming;filled++;}}checkpoint.successTmPlayerIds.push(p.tmPlayerId);checkpoint.fieldsFilled=(checkpoint.fieldsFilled??0)+filled;console.log(`profile HTTP: 200\nfields filled: ${filled}\nmissing after: ${missing(p)}\nresult: SUCCESS`)}catch(e:any){checkpoint.failedTmPlayerIds.push(p.tmPlayerId);console.log(`HTTP/profile result: FAILED ${e?.status??e?.code??"other"}
message: ${e?.message}
stack: ${e?.stack}`);if(e?.status===403||e?.status===429){checkpoint.stoppedReason=`HTTP ${e.status}`;checkpoint.processedTmPlayerIds.push(p.tmPlayerId); checkpoint.lastProcessedIndex=i;save();break}}checkpoint.processedTmPlayerIds.push(p.tmPlayerId); checkpoint.lastProcessedIndex=i;if(checkpoint.processedTmPlayerIds.length%10===0){save();console.log(`PROFILE ENRICHMENT STATUS\nprocessed: ${checkpoint.processedTmPlayerIds.length} / ${queue.length}\nsuccess: ${checkpoint.successTmPlayerIds.length}\nfailed: ${checkpoint.failedTmPlayerIds.length}\nfields filled total: ${checkpoint.fieldsFilled}\ncheckpoint saved: YES`)}await new Promise(r=>setTimeout(r,1200));}checkpoint.completedAt=new Date().toISOString();save();}
main();
