import "dotenv/config";
import { db } from "../src/lib/db";
import { calculateAndPersistPlayerOpportunity } from "../src/lib/intelligence/persistence";
import { playerScopeWhere, savePerformance, saveProfile } from "../src/lib/services/players";
import { finishRun, withSyncLock } from "../src/lib/services/runs";
import { TransfermarktClient } from "../src/lib/transfermarkt/client";
import { BudgetError, ProviderError } from "../src/lib/transfermarkt/errors";
import { TransfermarktProvider } from "../src/lib/transfermarkt/provider";
const BUDGET=100, A_LIMIT=73;
const valid=(p:{tmPlayerId:string;tmUrl:string})=>/^\d+$/.test(p.tmPlayerId)&&/^https?:\/\/(?:www\.)?transfermarkt\.[^/]+\/.+\/profil\/spieler\/\d+/i.test(p.tmUrl);
const profile=(p:any)=>[!!p.mainPosition?.trim()&&p.mainPosition!=="UNKNOWN",["LEFT","RIGHT"].includes(p.preferredFoot),!!p.portraitUrl?.trim(),!!p.contractExpires,p.marketValueEur!==null,(p.birthDate!==null||p.age!==null),p.representationStatus!=="UNKNOWN",p.clubId!==null].every(Boolean);
const sporting=(p:any)=>p.performances.some((x:any)=>x.season==="2026"&&x.competitionCode==="UZ1");
async function main(){await withSyncLock(async()=>{const players=await db.player.findMany({where:playerScopeWhere("UZBEKISTAN"),include:{performances:true},orderBy:{name:"asc"}});const A=players.filter(p=>valid(p)&&!sporting(p)&&profile(p)).slice(0,A_LIMIT);const aIds=new Set(A.map(p=>p.id));const B=players.filter(p=>valid(p)&&!aIds.has(p.id)&&!profile(p)).sort((a,b)=>{const ma=profile(a)?0:7,mb=profile(b)?0:7;return mb-ma||Number(a.profileLastSyncedAt!==null)-Number(b.profileLastSyncedAt!==null)||a.name.localeCompare(b.name)}).slice(0,BUDGET-A.length);if(new Set(B.map(p=>p.id)).size!==B.length||B.some(p=>aIds.has(p.id))||A.length+B.length>BUDGET)throw new Error("Invalid budget plan");console.log(JSON.stringify({budget:BUDGET,setA:A.length,setB:B.length,total:A.length+B.length}));const run=await db.syncRun.create({data:{type:"UZ1_BUDGETED_ENRICHMENT",metadata:JSON.stringify({A:A.map(p=>p.id),B:B.map(p=>p.id)})}});const provider=new TransfermarktProvider(new TransfermarktClient(run.id,BUDGET));let success=0,partial=0,failed=0,stopped=false;for(const [i,p] of [...A,...B].entries()){const kind=i<A.length?"PERFORMANCE":"PROFILE";try{if(kind==="PERFORMANCE"){const rows=await provider.performance(p.tmPlayerId);if(rows.some(r=>r.season==="2026"&&r.competitionCode==="UZ1")){await savePerformance(p.id,rows);success++}else partial++}else{await saveProfile(await provider.fetchPlayerProfile(p.tmPlayerId,p.tmUrl));success++}await calculateAndPersistPlayerOpportunity(p.id)}catch(e){if(e instanceof BudgetError||(e instanceof ProviderError&&["BLOCKED","CIRCUIT_OPEN","STOPPED"].includes(e.code))){stopped=true;break}failed++}finally{console.log(`[${i+1}/100] ${kind} ${p.name}`)}}await finishRun(run.id,stopped?new Error("Stopped by provider safety"):undefined,{success,partial,failed,setA:A.length,setB:B.length});console.log(JSON.stringify({success,partial,failed,stopped}))})}
try{await main()}finally{await db.$disconnect()}
